### ISSUE TITLE
Can't Enable Scroll Reverser

### ISSUE THREAD

**Issue by Mineinjava** [pilotmoon/Scroll-Reverser#98]
### I am using `v1.8` on macOS Big Sur
the scroll reverser icon is greyed out in the status bar. when I try to enable Scroll Reverser, the window shakes once and the checkbox becomes unchecked

<details>
  <summary>Images</summary>
  

![I can't click that box](https://user-images.githubusercontent.com/65673396/101423494-130cc100-38ae-11eb-8539-ba7a81924111.gif)
  
</details>

**Comment by invariant** [comment]
Hi there, thanks for the great report with GIF.
This is due to a bug in macOS which sometimes happens.
I have some steps for you which ought to resolve it:
1) Quit Scroll Reverser.
2) Ensure Scroll Reverser is located in your Applications folder and not in any other location.
3) Go to System preferences → Security & Privacy → Privacy
4) In the Accessibility category, use the "–" button to remove Scroll Reverser from the list.
5) Then click the "+" to add Scroll Reverser to the list again, and enable it.
6) Now restart Scroll Reverser.

**Comment by Mineinjava** [comment]
Thanks! that fixed the problem

**Comment by wookayin** [comment]
> Use the "–" button to remove Scroll Reverser from the list, then click the "+" to add it back.

It was important to do this step for **both of** Accessibility and Input Monitoring.
